openlawteam/openlaw-client

build.sbt
js/src/APIClient.js
npm.README.md
openlaw.webpack.config.js
package-lock.json
package.json
webpack.common.js

pieced together more info of how axios works with webpack, node, and web from several sources including these:
https://github.com/axios/axios/issues/456
https://lmiller1990.github.io/electic/posts/server_side_hydration_with_vue_and_webpack.html
Tested local package with nodejs and react dummy projects and openlaw-backend and all seem to be working fine. Changes in this pr also include some cleanup.
If this looks good and merged into master, I can patch update to 0.1.4 and publish again.

allow npm package to work in nodejs

---

.github/main.workflow
Dockerfile
scripts/entrypoint.sh

Quick script that should fix the CI error on release seen in https://github.com/openlawteam/openlaw-client/runs/114468168, which was caused by Github Actions overriding the default WORKDIR during their wrapper docker run (in a way that actually makes sense for most use cases, but for us causes the layer cached `node_modules` directory to not be seen since we're now in the wrong project directory).
In addition, this should also help guard against potential Scala caching issues stemming from `$HOME` being overridden, in other usages in the future.

custom entrypoint script to avoid CI overrides

---

project/plugins.sbt

Removed commented out plugins from builder migration largely left over from openlaw-core repo.
Added context to TODOs on plugins that are still open questions, will follow up in this thread with Questions.

SBT plugin cleanup

---

docs/ReleaseProcess.md

- Separate PR process instructions from actual release process.
- Document some technical details about how release stage works behind the scenes.
- Add documentation about running linters.
Just my thoughts, edits warmly welcomed!

Some proposed additions to the release process docs

---

package-lock.json
package.json
scripts/release.sh

The intros a release script that detects semver pre-release SemVer version strings and automatically append `--tag prerelease` to the npm publish commands when they are detected. This should restore proper behavior whereby end users will not automatically get a prerelease version on install unless explicitly requested, which will give us the option to push prerelease builds (for example, like when testing our build process recently) with more controlled impact on end users.
The origin of this issue stems from NPM now starting to use their own "dist tags" that must be explicitly set, when they used to respect SemVer directly. 😞 
See: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420
I briefly skimmed the source code of the newly added npm package that handles this and checked …

Semantic Version prerelease-aware script for `npm publish`

---

build.sbt
src/main/scala/org/adridadou/openlaw/client/Openlaw.scala

It adds the `externalCallStructures` to the `execute` function, so the VM can evaluate templates with  `ExternalCallType` variables. 
The `externalCallStructures` provides the ABIs of each integrated service in Openlaw App.
The PRs relies on a new release of openlaw-core with: https://github.com/openlawteam/openlaw-core/pull/140

Execute template with external call structures

---

build.sbt
src/main/scala/org/adridadou/openlaw/client/Openlaw.scala

This PR adds a new function to Openlaw.scala that allows the client to generate the json value of a ExternalSignature type based on the input parameters.
It also changes the get the Identity and check the signatories, given that ExternaSignature is an Identity type, we need to consider that in these 2 functions as well.
Dependencies:
1. https://github.com/openlawteam/openlaw-core/pull/165

External signature integration

---

src/main/scala/org/adridadou/openlaw/client/Openlaw.scala

One line change to access `message` property of the error. Helps us on the front-end. Tested locally by pulling into app.
**From semi-unusable:**
```
{ isError: true,
errorMessage:
$c_Lorg_adridadou_openlaw_result_FailureMessage {
'message$1':
'Unexpected end of input, expected keyChar, variableTypeDefinition, ws, \'|\', stringDefinition, \' \', \']\' or \'.\' (line 1, column 15):\n[[Company Name\n              ^',
'idOpt$1': $c_s_None$ {},
'e$1':
$c_jl_RuntimeException {
's$1':
'Unexpected end of input, expected keyChar, variableTypeDefinition, ws, \'|\', stringDefinition, \' \', \']\' or \'.\' (line 1, column 15):\n[[Company Name\n              ^',
'e$1': null,
'enableSuppression$1': true,
'writableStackTrace$1': true,
'stackTrace$1': null,
'suppressed$1': null,
stackdata: [Circular] }, …
```

Outputs the error message as a string on compileTemplate error

---

.github/workflows/debug.yml

This is a temporary workflow to dump the event data payload on all pushes in order to provide some actual production data for developing better CI scripts in the future.

Debug workflow to dump action payload

---

.github/workflows/lint.yml

Replaces shellcheck action in deprecated GitHub `actions/bin` with https://github.com/reviewdog/action-shellcheck.
See more info on how [GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#github_token-secret). For the other inputs, including `path` and `pattern`, looks like the defaults are sufficient to cover the current `.sh` files, but let me know if you think we need to adjust.

update shellcheck action

---

build.sbt
project/plugins.sbt

Also requires `sbt-scalajs` to be updated to v0.6.31 to match same update made in openlawteam/openlaw-core#198.

bump openlaw-core to 0.1.49

---

.gitignore
build.sbt

- Bump openlaw-core dependency to latest `0.1.51`.
- Update `.gitignore` with one more file related to Metals Scala language server tool for Visual Studio Code (https://scalameta.org/metals/docs/editors/vscode.html#gitignore-projectmetalssbt-metals-and-bloop)

openlaw-core 0.1.51

---

build.sbt

Bumps openlaw-core dependency to latest 0.1.52.
`client.js` generates fine and the build completes with no errors after the core bump.

openlaw-core 0.1.52

---

build.sbt

Fixes issue where `central.maven.org` is no longer resolving.
More details about the breaking changes with the repository endpoints:
https://central.sonatype.org/articles/2019/Nov/15/non-canonical-urls-will-be-redirected-today/
https://central.sonatype.org/articles/2018/Dec/17/ssl-endpoints/

update Maven Central endpoint

---

build.sbt

Re-opening this PR after resolving the Maven Central endpoint issue
Catches client up with latest version of openlaw-core.

bump openlaw-core to 0.1.57

---

package-lock.json
package.json

Reverts openlawteam/openlaw-client#166
We'll need to do further investigating, but for now we are downgrading `axios` dependency back to `0.18.1`. The bump is causing failing JS tests when the `openlaw` dependency is imported into openlaw-app.

Revert "Bump axios from 0.18.1 to 0.19.2"

---

build.sbt

- bumps openlaw-core to 0.1.58 (no compile issues in generating `client.js`)

bump openlaw-core to 0.1.58

---

js/src/APIClient.js

Route and endpoint for the `disableFlowAccessToken` call were removed from openlaw-app as part of the Flow access updates.

remove deprecated disableFlowAccessToken call

---

build.sbt
src/main/scala/org/adridadou/openlaw/client/Openlaw.scala

adding optional parameter to pass the contract creation date (to be used in the execution)
bumps to latest openlaw-core release `0.1.62`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/178)

fix compile

---

build.sbt

Bumps openlaw-core to latest release version.

bump openlaw-core 0.1.63

---

.github/workflows/lint.yml

shellcheck is preinstalled on current version of GHA virtual env, so just run it directly instead of using an action at all.
The environment version in this sub-job is pinned since it now relies on something being present in the environment's preinstalled software, as a safety hedge just in case this is removed as preinstalled software when latest of ubuntu for GHA changes in ~2 years.
(conforming change with openlawteam/openlaw-app#3140)

build(ci): replace third-party shellcheck action
