openlawteam/openlaw-client

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
Work in progress, do not merge.
=> Fix remaining render call in client.

js/src/APIClient.js, package.json
updates the APIClient call to match recent update to address search on the server side
=> fix searchAddress

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
@Jdville03 David has fixed the compile issues so, assuming it looks good with your tests, this should be ready for merge. (In this case, we can safely ignore the CircleCI build error as those tests have not been set up yet).
=> Upgrading core version to 0.1.13 

js/src/APIClient.js
Hey, I'm not sure what's the process of adding new API calls to this repo. So let's discuss this on the PR.
Anything else? I guess I need to update the Docs too?
=> Added new flow functions

build.sbt
This should trigger the build with auto publish on the merge.
=> core dependency update

Dockerfile, package-lock.json, package.json
newer np version should resolve the upstream branch issue for the publish script
=> update build to use npm ci and np dependency update

Dockerfile
these were added in previous attempts to get the automated release to work
=> remove unused git configs

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
=> Updated for new core error types.

js/src/APIClient.js, package-lock.json
This update goes along with the updates being made in `openlaw` backend for adding a global accessToken to flows.
Another client release will need to be made with these updates before merging openlawteam/openlaw#2188.
=> add accessToken and flow related calls

js/src/APIClient.js
We will do a minor version release to 0.2.0 with this change.
=> remove getUserDetails from APIClient (dead code in backend now)

build.sbt, js/src/APIClient.js, package.json, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
check for potential issues with getting execution results from serialized result
=> update erc712 call

src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
=> fix / update checkValidity

package-lock.json, package.json
Consolidates dependency bump PRs: #109, #110, #111, #112, #113.
Successful build and things look good with imported local package in openlaw-app.
=> Weekly dependency bumps

package-lock.json, package.json
Consolidates dependency bumps PRs: #133, #134, #135, #136, #137.
Updated dependencies tested with successful build. openlaw-app builds and runs and all enabled tests pass with imported local package.
=> Monthly (Oct 2019) dependency bumps

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/165)
=> Core 0.1.56

.github/workflows/lint.yml, .scalafmt.conf, .vscode/extensions.json, .vscode/settings.json, Makefile, README.md, build.sbt, project/plugins.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
=> integrate scalafmt code formatting scaffolding

rollup.config.js
* Replaces `() => {}` with `undefined` for conditional `terser` plugin.
* Object end comma lint (sorry, Prettier goes wild)
=> Fix dev build

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/187)
=> apply changes based on core changes

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/191)
=> Fix date and formatting

build.sbt, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/192)
=> update core version and code accordingly

build.sbt, js/src/APIClient.js, src/main/scala/org/adridadou/openlaw/client/Openlaw.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openlawteam/openlaw-client/212)
=> Remove drafts

build.sbt
Need a release once this is merged.
=> Updated core version.
